apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-nginx-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Backend</title>
    </head>
    <body style="font-family: Arial; text-align: center; margin-top: 100px;">
      <h1>Backend</h1>
    </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-nginx
  template:
    metadata:
      labels:
        app: backend-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
      volumes:
        - name: html-volume
          configMap:
            name: backend-nginx-html
---
apiVersion: v1
kind: Service
metadata:
  name: backend-nginx
spec:
  selector:
    app: backend-nginx
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
